# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'PHILIPMobiletools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PHILIPMobiletools
  
#pod 'YYModel'
#pod 'Protobuf'
#pod 'UMCCommon'
#pod 'SDWebImage'
pod 'AFNetworking'
pod 'Masonry'
pod 'TZImagePickerController'

end
